name: test

on:
  push:
    branches:
      - main
      - develop
      - 'chore/**'
      - 'bug/**'
      - 'feature/**'
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node packages
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit test
        run: npm run test

      - name: Run end to end test
        run: npm run e2e
