name: CI and CD

on:
  push:
    branches:
      - main
      - develop
      - "chore/**"
      - "bug/**"
      - "feature/**"
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Update Chrome
        run: sudo apt-get update && sudo apt-get install google-chrome-stable

      - name: Install node packages
        run: npm install

      - name: Run lint
        run: npm run lint

  deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
      HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}

    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git
          git push -f production origin/main:refs/heads/master
      - name: Deploy Staging
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git
          git push -f staging origin/chore/ci-cd:refs/heads/master
